
POST http://localhost:9001/users/check
Content-Type: application/json

{
"login" : "joe",
"password": "joe1234"
}

###

POST http://localhost:9002/bets
Content-Type: application/json
Authorization: joe:joe1234

< requests/bet.json

###
GET http://localhost:9002/bets/joe
Content-Type: application/json